name: rag-env
channels: [conda-forge, defaults]
dependencies:
  - python=3.12
  - pip
  - pip:
    - llama-index
    - llama-index-embeddings-huggingface
    - python-dotenv
    - PyYAML
    - sentence-transformers
    - torch
    - pytest
    - pytest-mock
    # We might add a specific vector store like chromadb or faiss-cpu later
    # e.g., - chromadb 
    # e.g., - faiss-cpu
