name: llm-agent
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - pip
  - pip:
      - faiss-cpu
      - pdfminer.six
      - sentence-transformers
      - bibtexparser
      - fastapi
      - uvicorn[standard]
      - requests
      - PyYAML 
      - beautifulsoup4
      - python-dotenv
      - torch
      - PyPDF2
      - Unidecode
      - rich
      - pydantic-settings